/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.panitia;

import com.jtk.pengelolaanujian.controller.panitiaController.CreateUjianController;
import com.jtk.pengelolaanujian.controller.panitiaController.EventController;
import com.jtk.pengelolaanujian.entity.Event;
import com.jtk.pengelolaanujian.entity.MataKuliah;
import com.jtk.pengelolaanujian.util.CommonHelper;
import com.jtk.pengelolaanujian.util.EnumPanel;
import com.jtk.pengelolaanujian.view.LoginPanel;
import com.jtk.pengelolaanujian.view.util.SearchDialog;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Zulkhair Abdullah D
 */
public class CreateUjian extends javax.swing.JPanel {

    private MataKuliah mataKuliah;
    private Event event = LoginPanel.getEvent();

    /**
     * Creates new form CreateUjian
     */
    public CreateUjian() {
        initComponents();
        textEvent.setText(CommonHelper.createTahun(event));
        spinDurasi.setModel(CommonHelper.createDurasiSpinnerModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNamaUjian = new javax.swing.JLabel();
        textNamaUjian = new javax.swing.JTextField();
        labelEventUjian = new javax.swing.JLabel();
        dateUjianMulai = new com.toedter.calendar.JDateChooser();
        labelTanggal = new javax.swing.JLabel();
        labelPukul = new javax.swing.JLabel();
        textJam = new javax.swing.JTextField();
        labelPukul1 = new javax.swing.JLabel();
        textMenit = new javax.swing.JTextField();
        labelArsipSoal = new javax.swing.JLabel();
        textMatkul = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnCreateUjian = new javax.swing.JButton();
        textEvent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinDurasi = new javax.swing.JSpinner();
        labelArsipSoal1 = new javax.swing.JLabel();
        textKodeSoal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboSifatSoal = new javax.swing.JComboBox();

        labelNamaUjian.setText("Nama Ujian");

        labelEventUjian.setText("Event Ujian");

        dateUjianMulai.setPreferredSize(new java.awt.Dimension(90, 20));

        labelTanggal.setText("Tanggal");

        labelPukul.setText("Pukul");

        labelPukul1.setText(":");

        labelArsipSoal.setText("Mata Kuliah");

        textMatkul.setEditable(false);

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnCreateUjian.setText("Create Ujian");
        btnCreateUjian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUjianActionPerformed(evt);
            }
        });

        textEvent.setEditable(false);
        textEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEventActionPerformed(evt);
            }
        });

        jLabel1.setText("Durasi");

        jLabel2.setText("Menit");

        labelArsipSoal1.setText("Kode Soal");

        jLabel3.setText("Sifat Soal");

        cboSifatSoal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buka Buku", "Tutup Buku" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEventUjian)
                            .addComponent(labelTanggal)
                            .addComponent(labelArsipSoal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelNamaUjian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelArsipSoal1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCreateUjian)
                                    .addComponent(textKodeSoal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNamaUjian, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textMatkul, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textEvent, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateUjianMulai, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelPukul)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textJam, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelPukul1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboSifatSoal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBrowse)))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEventUjian)
                    .addComponent(textEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaUjian)
                    .addComponent(textNamaUjian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArsipSoal)
                    .addComponent(textMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArsipSoal1)
                    .addComponent(textKodeSoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboSifatSoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPukul)
                        .addComponent(textJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPukul1)
                        .addComponent(textMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateUjianMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(spinDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateUjian)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEventActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        mataKuliah = new MataKuliah();
        SearchDialog searchDialog = new SearchDialog(null, true, mataKuliah, EnumPanel.SEARCH_SOAL);
        searchDialog.show();
        textMatkul.setText(mataKuliah.getMatkulNama());
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnCreateUjianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUjianActionPerformed
        if (textNamaUjian.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi nama ujian", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (mataKuliah == null) {
            JOptionPane.showMessageDialog(this, "Harap pilih mata kuliah", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (textKodeSoal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi kode soal", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (textKodeSoal.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Kode soal tidak boleh melebihi 5 karakter", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (dateUjianMulai.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Harap isi tanggal mulai ujian", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (textJam.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi jam mulai ujian", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (!CommonHelper.isStringNumberMaxMin(textJam.getText(), 23, 0)) {
            JOptionPane.showMessageDialog(this, "Harap isi format jam dengan benar", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (textMenit.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi menit mulai ujian", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (!CommonHelper.isStringNumberMaxMin(textMenit.getText(), 59, 0)) {
            JOptionPane.showMessageDialog(this, "Harap isi format menit dengan benar", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (spinDurasi.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Harap isi durasi ujian", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else if (!CommonHelper.isStringNumberMaxMin(spinDurasi.getValue().toString(), 1000, 1)) {
            JOptionPane.showMessageDialog(this, "Harap isi format durasi dengan benar", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else {
            CreateUjianController controller = new CreateUjianController();
            Date date = new Date();
            date.setTime(date.getTime());
            date.setHours(Integer.parseInt(textJam.getText()));
            date.setMinutes(Integer.parseInt(textMenit.getText()));
            date.setSeconds(0);

            if (controller.createUjian(event.getKode(), textNamaUjian.getText(),
                    textKodeSoal.getText(), mataKuliah, cboSifatSoal.getSelectedItem().toString(),
                    date, (int) spinDurasi.getValue())) {
                textNamaUjian.setText("");
                mataKuliah = new MataKuliah();
                textMatkul.setText("");
                textKodeSoal.setText("");
                cboSifatSoal.setSelectedIndex(0);
                textJam.setText("");
                textMenit.setText("");
                spinDurasi.setModel(CommonHelper.createDurasiSpinnerModel());
            }
        }
    }//GEN-LAST:event_btnCreateUjianActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCreateUjian;
    private javax.swing.JComboBox cboSifatSoal;
    private com.toedter.calendar.JDateChooser dateUjianMulai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelArsipSoal;
    private javax.swing.JLabel labelArsipSoal1;
    private javax.swing.JLabel labelEventUjian;
    private javax.swing.JLabel labelNamaUjian;
    private javax.swing.JLabel labelPukul;
    private javax.swing.JLabel labelPukul1;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JSpinner spinDurasi;
    private javax.swing.JTextField textEvent;
    private javax.swing.JTextField textJam;
    private javax.swing.JTextField textKodeSoal;
    private javax.swing.JTextField textMatkul;
    private javax.swing.JTextField textMenit;
    private javax.swing.JTextField textNamaUjian;
    // End of variables declaration//GEN-END:variables

}
