/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jtk.pengelolaanujian.view.panitia;

import com.jtk.pengelolaanujian.controller.panitiaController.EventController;
import com.jtk.pengelolaanujian.entity.Event;
import com.jtk.pengelolaanujian.entity.Soal;
import com.jtk.pengelolaanujian.entity.Staf;
import com.jtk.pengelolaanujian.util.EnumPanel;
import com.jtk.pengelolaanujian.view.util.SearchDialog;

/**
 *
 * @author Zulkhair Abdullah D
 */
public class CreateUjian extends javax.swing.JPanel {
    EventController eventController = new EventController();
    Event event;
    /**
     * Creates new form CreateUjian
     */
    public CreateUjian() {
        initComponents();    
        String string = null;
        event=eventController.getListEvent();
        System.out.println(event.getKode().toString());        
        System.out.println(createTahun());            
        textEvent.setText(createTahun());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNamaUjian = new javax.swing.JLabel();
        textNamaUjian = new javax.swing.JTextField();
        labelEventUjian = new javax.swing.JLabel();
        dateUjianMulai = new com.toedter.calendar.JDateChooser();
        labelTanggal = new javax.swing.JLabel();
        labelPukul = new javax.swing.JLabel();
        textJam = new javax.swing.JTextField();
        labelPukul1 = new javax.swing.JLabel();
        textMenit = new javax.swing.JTextField();
        labelArsipSoal = new javax.swing.JLabel();
        textArsipSoal = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnCreateUjian = new javax.swing.JButton();
        textEvent = new javax.swing.JTextField();

        labelNamaUjian.setText("Nama Ujian");

        labelEventUjian.setText("Event Ujian");

        dateUjianMulai.setPreferredSize(new java.awt.Dimension(90, 20));

        labelTanggal.setText("Tanggal");

        labelPukul.setText("Pukul");

        labelPukul1.setText(":");

        labelArsipSoal.setText("Arsip Soal");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnCreateUjian.setText("Create Ujian");

        textEvent.setEditable(false);
        textEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreateUjian)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEventUjian)
                            .addComponent(labelNamaUjian)
                            .addComponent(labelTanggal)
                            .addComponent(labelArsipSoal))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textNamaUjian, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textArsipSoal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEvent, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateUjianMulai, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBrowse)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPukul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textJam, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPukul1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEventUjian)
                    .addComponent(textEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaUjian)
                    .addComponent(textNamaUjian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArsipSoal)
                    .addComponent(textArsipSoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPukul)
                        .addComponent(textJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPukul1)
                        .addComponent(textMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateUjianMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(btnCreateUjian)
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEventActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textEventActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_btnBrowseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCreateUjian;
    private com.toedter.calendar.JDateChooser dateUjianMulai;
    private javax.swing.JLabel labelArsipSoal;
    private javax.swing.JLabel labelEventUjian;
    private javax.swing.JLabel labelNamaUjian;
    private javax.swing.JLabel labelPukul;
    private javax.swing.JLabel labelPukul1;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTextField textArsipSoal;
    private javax.swing.JTextField textEvent;
    private javax.swing.JTextField textJam;
    private javax.swing.JTextField textMenit;
    private javax.swing.JTextField textNamaUjian;
    // End of variables declaration//GEN-END:variables

    private String createTahun() {
        String string;
        string = "Ujian ";
        char[] a;
        a = new char[5];
        a=event.getKode().toCharArray();                
               
        if(a[3]=='T'){
            string = string + "Tengah semester ";
        }else{
            string = string + "Akhir semester ";
        }
        
        if(a[2]=='1'){
            string = string + "Genap ";
        }else{
            string = string + "Ganjil ";
        }
        string = string+"Tahun 20"+a[0]+a[1];
        
        return string;
    }
}
