/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.panitia;

import com.jtk.pengelolaanujian.controller.panitiaController.PrintSoalController;
import com.jtk.pengelolaanujian.view.panitia.PrintSoalDialog;

/**
 *
 * @author pahlevi
 */
public class PrintSoal extends javax.swing.JPanel {

    PrintSoalController printSoalController = new PrintSoalController();

    /**
     * Creates new form PrintSola
     */
    public PrintSoal() {
        initComponents();
    }

    public void preparation() {
        printSoalController.viewTableListPrintSoal(tableViewListPrintSoal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewListPrintSoal = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();

        tableViewListPrintSoal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Soal", "Kode Matkul", "Mata Kuliah", "Dosen Pengampu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableViewListPrintSoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableViewListPrintSoalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableViewListPrintSoal);
        if (tableViewListPrintSoal.getColumnModel().getColumnCount() > 0) {
            tableViewListPrintSoal.getColumnModel().getColumn(0).setResizable(false);
            tableViewListPrintSoal.getColumnModel().getColumn(1).setResizable(false);
            tableViewListPrintSoal.getColumnModel().getColumn(2).setResizable(false);
            tableViewListPrintSoal.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("List Soal Siap Print");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel22)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel22)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableViewListPrintSoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewListPrintSoalMouseClicked
        String kodeSoal = tableViewListPrintSoal.getValueAt(tableViewListPrintSoal.getSelectedRow(), 0).toString();
        PrintSoalDialog printSoalDialog = new PrintSoalDialog(null, true, kodeSoal);
        printSoalDialog.show();
    }//GEN-LAST:event_tableViewListPrintSoalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableViewListPrintSoal;
    // End of variables declaration//GEN-END:variables
}
