/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.admin;

import com.jtk.pengelolaanujian.controller.admin.EditUserController;
import com.jtk.pengelolaanujian.entity.Staf;
import com.jtk.pengelolaanujian.entity.User;
import com.jtk.pengelolaanujian.util.EnumPanel;
import com.jtk.pengelolaanujian.view.util.SearchDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author pahlevi
 */
public class EditUser extends javax.swing.JPanel {

    private User user;

    /**
     * Creates new form EditUser
     */
    public EditUser() {
        initComponents();
        textUsername.setEditable(false);
    }
    
    public void preparation(){
        textUsername.setText("");
        radAktif.setSelected(false);
        radNonAktif.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        radAktif = new javax.swing.JRadioButton();
        radNonAktif = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(640, 625));
        setPreferredSize(new java.awt.Dimension(640, 625));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Username");

        textUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsernameActionPerformed(evt);
            }
        });

        btnBrowse.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBrowse.setText("Cari");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Status");

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        buttonGroup1.add(radAktif);
        radAktif.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        radAktif.setText("Aktif");
        radAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAktifActionPerformed(evt);
            }
        });

        buttonGroup1.add(radNonAktif);
        radNonAktif.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        radNonAktif.setText("Non-Aktif");
        radNonAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNonAktifActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Edit User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(radAktif)
                        .addGap(19, 19, 19)
                        .addComponent(radNonAktif))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radAktif)
                    .addComponent(radNonAktif))
                .addGap(81, 81, 81)
                .addComponent(btnSimpan)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        user = new User();
        Staf staf = new Staf();
        SearchDialog searchStafDialog = new SearchDialog(null, true, staf, EnumPanel.EDIT_USER);
        searchStafDialog.show();
        user = staf.getUserQuery();
        if (user != null) {
            textUsername.setText(user.getUserUsername());
            if (user.isUserActive()) {
                radAktif.setSelected(true);
            } else {
                radNonAktif.setSelected(true);
            }
        }


    }//GEN-LAST:event_btnBrowseActionPerformed

    private void textUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsernameActionPerformed

    private void radAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAktifActionPerformed
        user.setUserActive(true);
    }//GEN-LAST:event_radAktifActionPerformed

    private void radNonAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNonAktifActionPerformed
        user.setUserActive(false);
    }//GEN-LAST:event_radNonAktifActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        EditUserController editUserController = new EditUserController();
        if (editUserController.editUser(user)) {
            JOptionPane.showMessageDialog(this, "Edit user berhasil dilakukan");
        } else {
            JOptionPane.showMessageDialog(this, "Edit user gagal dilakukan", "Gagal", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton radAktif;
    private javax.swing.JRadioButton radNonAktif;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
