/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.admin;

import com.jtk.pengelolaanujian.view.util.SearchDialog;
import com.jtk.pengelolaanujian.controller.admin.RegistrasiUserController;
import com.jtk.pengelolaanujian.entity.Staf;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author pahlevi
 */
public class RegistrasiUser extends javax.swing.JPanel {

    RegistrasiUserController registrasiUserController = new RegistrasiUserController();
    private Staf staf;

    /**
     * Creates new form AssignRole
     */
    public RegistrasiUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        textUsername = new javax.swing.JTextField();
        btnRegistrasi = new javax.swing.JButton();
        textPasswordRetype = new javax.swing.JPasswordField();
        textPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(609, 462));

        jLabel1.setText("Nama");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        textNama.setEditable(false);

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnRegistrasi.setText("Registrasi");
        btnRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiActionPerformed(evt);
            }
        });

        jLabel4.setText("Retype Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrasi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(textNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPasswordRetype, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowse)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPasswordRetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addComponent(btnRegistrasi)
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        staf = new Staf();
        SearchDialog searchStafDialog = new SearchDialog(null, true, staf);
        searchStafDialog.show();
        textNama.setText(staf.getStafNama());
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiActionPerformed
        if(textNama.getText() != null && !textNama.getText().isEmpty()) {
            if (textUsername.getText() != null && !textUsername.getText().isEmpty()) {
                if (textPassword.getText().equals(textPasswordRetype.getText())) {
                    if (textPassword.getText() != null && !textPassword.getText().isEmpty()) {
                        registrasiUserController.registrasiUser(staf, textUsername.getText(), textPassword.getText());
                        JOptionPane.showMessageDialog(this, "User baru berhasil diinputkan, Nama ->"+staf.getStafNama());
                        textNama.setText("");
                        textPassword.setText("");
                        textPasswordRetype.setText("");
                        textUsername.setText("");
                    }else{
                        JOptionPane.showMessageDialog(this, "harap isi password");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password yg anda inputkan tidak sama");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Harap isi username dan atau password terlebih dahulu");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Harap isi Nama");
        }        
    }//GEN-LAST:event_btnRegistrasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnRegistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textNama;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JPasswordField textPasswordRetype;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables

    private void registrasiUser(String nipUser, JTextField textNama, JPasswordField textPassword) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
