/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.dashboard;

import com.jtk.pengelolaanujian.view.MainFrame;

/**
 *
 * @author Zulkhair Abdullah D
 */
public class DashboardPanel extends javax.swing.JPanel {

    MainFrame mainFrame;

    /**
     * Creates new form DashboardPanel
     * @param mainFrame
     */
    public DashboardPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }
    
    public void preparation(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        chartPanel11 = new com.jtk.pengelolaanujian.view.dashboard.ChartPanel1();
        jScrollPane2 = new javax.swing.JScrollPane();
        chartPanel21 = new com.jtk.pengelolaanujian.view.dashboard.ChartPanel2();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jScrollPane1.setViewportView(chartPanel11);

        jTabbedPane1.addTab("Pie", jScrollPane1);

        jScrollPane2.setViewportView(chartPanel21);

        jTabbedPane1.addTab("Batang", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jtk.pengelolaanujian.view.dashboard.ChartPanel1 chartPanel11;
    private com.jtk.pengelolaanujian.view.dashboard.ChartPanel2 chartPanel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
