/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.dashboard;

import com.jtk.pengelolaanujian.controller.dashboard.TriggerDashboardController;
import com.jtk.pengelolaanujian.entity.Event;
import java.util.Arrays;

/**
 *
 * @author pahlevi
 */
public class StatusEvent extends javax.swing.JPanel {

    TriggerDashboardController triggerDashboardController = new TriggerDashboardController();
    Event event;

    /**
     * Creates new form StatusEvent
     */
    public StatusEvent() {
        initComponents();
        //progresEvent.setValue();
    }

    public void preparation() {
        event = triggerDashboardController.getListEvent();
        String ujian = "Ujian ";
        char[] a;
        a = event.getKode().toCharArray();

        if (a[3] == 'T') {
            ujian = ujian + "Tengah semester ";
        } else {
            ujian = ujian + "Akhir semester ";
        }

        if (a[2] == '1') {
            ujian = ujian + "Genap ";
        } else {
            ujian = ujian + "Ganjil ";
        }
        ujian = ujian + "Tahun 20" + a[0] + a[1];

        textUjian.setText(ujian);
        textEventMulai.setText(event.getTanggalMulai().toString());
        textEventAkhir.setText(event.getTanggalSelesai().toString());
        textNilaiAkhir.setText(event.getUploadNilaiSelesai().toString());
        textSoalMulai.setText(event.getUploadMulai().toString());
        textSoalAkhir.setText(event.getUploadSelesai().toString());
        textVnvMulai.setText(event.getVnvMulai().toString());
        textVnvAkhir.setText(event.getVnvSelesai().toString());

        triggerDashboardController.viewTableUjian(tableUjian);
        progresEvent.setValue(20);
        piePanelUjian1.preparation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUjian = new javax.swing.JLabel();
        textUjian = new javax.swing.JTextField();
        textEventMulai = new javax.swing.JTextField();
        textEventAkhir = new javax.swing.JTextField();
        labelPelaksanaan = new javax.swing.JLabel();
        textSoalMulai = new javax.swing.JTextField();
        textSoalAkhir = new javax.swing.JTextField();
        textVnvMulai = new javax.swing.JTextField();
        textVnvAkhir = new javax.swing.JTextField();
        textNilaiAkhir = new javax.swing.JTextField();
        labelUploadSoal = new javax.swing.JLabel();
        labelBerakhirPada = new javax.swing.JLabel();
        labelUploadSoal2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelUploadSoal3 = new javax.swing.JLabel();
        labelHeader2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUjian = new javax.swing.JTable();
        labelHeader3 = new javax.swing.JLabel();
        piePanelUjian1 = new com.jtk.pengelolaanujian.view.dashboard.PiePanelUjian();
        labelUploadSoal4 = new javax.swing.JLabel();
        progresEvent = new javax.swing.JProgressBar();
        labelHeader4 = new javax.swing.JLabel();
        textSearch = new javax.swing.JTextField();
        labelUploadSoal5 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHeader1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHeader1.setForeground(new java.awt.Color(0, 153, 153));
        labelHeader1.setText("Ujian yang akan diselenggarakan");
        add(labelHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 77, -1, -1));

        labelUjian.setText("Ujian");
        add(labelUjian, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 54, -1, -1));

        textUjian.setEditable(false);
        textUjian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUjianActionPerformed(evt);
            }
        });
        add(textUjian, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 260, -1));

        textEventMulai.setEditable(false);
        textEventMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEventMulaiActionPerformed(evt);
            }
        });
        add(textEventMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 83, 99, -1));

        textEventAkhir.setEditable(false);
        textEventAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEventAkhirActionPerformed(evt);
            }
        });
        add(textEventAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 83, 99, -1));

        labelPelaksanaan.setText("Pelaksanaan");
        add(labelPelaksanaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 86, -1, -1));

        textSoalMulai.setEditable(false);
        textSoalMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSoalMulaiActionPerformed(evt);
            }
        });
        add(textSoalMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 121, 99, -1));

        textSoalAkhir.setEditable(false);
        textSoalAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSoalAkhirActionPerformed(evt);
            }
        });
        add(textSoalAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 121, 99, -1));

        textVnvMulai.setEditable(false);
        textVnvMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textVnvMulaiActionPerformed(evt);
            }
        });
        add(textVnvMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 159, 99, -1));

        textVnvAkhir.setEditable(false);
        textVnvAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textVnvAkhirActionPerformed(evt);
            }
        });
        add(textVnvAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 159, 99, -1));

        textNilaiAkhir.setEditable(false);
        textNilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiAkhirActionPerformed(evt);
            }
        });
        add(textNilaiAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 99, -1));

        labelUploadSoal.setText("Upload Soal");
        add(labelUploadSoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 124, -1, -1));

        labelBerakhirPada.setText("Berakhir Pada");
        add(labelBerakhirPada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        labelUploadSoal2.setText("Upload VNV");
        add(labelUploadSoal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 162, -1, -1));

        jLabel4.setText("-");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 124, -1, -1));

        jLabel5.setText("-");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 162, -1, -1));

        jLabel6.setText("-");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 86, -1, -1));

        jLabel7.setText("-");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 162, -1, -1));

        labelUploadSoal3.setText("Detail Informasi Umum mengenai penyelenggaraan Event Ujian ");
        add(labelUploadSoal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        labelHeader2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelHeader2.setForeground(new java.awt.Color(0, 153, 153));
        labelHeader2.setText("Keberlangsungan Event");
        add(labelHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, 20));

        tableUjian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ujian", "Kode Soal", "Kode Matkul", "Pelaksanaan", "Ruangan", "Pengawas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableUjian);
        if (tableUjian.getColumnModel().getColumnCount() > 0) {
            tableUjian.getColumnModel().getColumn(0).setResizable(false);
            tableUjian.getColumnModel().getColumn(1).setResizable(false);
            tableUjian.getColumnModel().getColumn(2).setResizable(false);
            tableUjian.getColumnModel().getColumn(3).setResizable(false);
            tableUjian.getColumnModel().getColumn(4).setResizable(false);
            tableUjian.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 670, 230));

        labelHeader3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHeader3.setForeground(new java.awt.Color(0, 153, 153));
        labelHeader3.setText("Beranda Informasi Event Ujian Terkini");
        add(labelHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, -1));

        javax.swing.GroupLayout piePanelUjian1Layout = new javax.swing.GroupLayout(piePanelUjian1);
        piePanelUjian1.setLayout(piePanelUjian1Layout);
        piePanelUjian1Layout.setHorizontalGroup(
            piePanelUjian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        piePanelUjian1Layout.setVerticalGroup(
            piePanelUjian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        add(piePanelUjian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 240, 190));

        labelUploadSoal4.setText("Search Ujian");
        add(labelUploadSoal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        add(progresEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 230, -1));

        labelHeader4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHeader4.setForeground(new java.awt.Color(0, 153, 153));
        labelHeader4.setText("Ujian Status");
        add(labelHeader4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 20));

        textSearch.setText("Cari berdasakan nama");
        textSearch.setToolTipText("Cari berdasakan nama");
        textSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchActionPerformed(evt);
            }
        });
        textSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSearchFocusLost(evt);
            }
        });
        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSearchKeyReleased(evt);
            }
        });
        add(textSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 210, -1));

        labelUploadSoal5.setText("Upload Nilai");
        add(labelUploadSoal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void textUjianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUjianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUjianActionPerformed

    private void textEventMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEventMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEventMulaiActionPerformed

    private void textEventAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEventAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEventAkhirActionPerformed

    private void textSoalMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoalMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSoalMulaiActionPerformed

    private void textSoalAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoalAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSoalAkhirActionPerformed

    private void textVnvMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textVnvMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textVnvMulaiActionPerformed

    private void textVnvAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textVnvAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textVnvAkhirActionPerformed

    private void textNilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiAkhirActionPerformed

    private void textSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchActionPerformed

    private void textSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSearchFocusGained
        // TODO add your handling code here:
        textSearch.setText("");
    }//GEN-LAST:event_textSearchFocusGained

    private void textSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSearchFocusLost
        // TODO add your handling code here:
        textSearch.setText("Cari berdasakan nama");
    }//GEN-LAST:event_textSearchFocusLost

    private void textSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyReleased
        // TODO add your handling code here:
        triggerDashboardController.viewTableUjian(tableUjian, textSearch.getText());
    }//GEN-LAST:event_textSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBerakhirPada;
    private javax.swing.JLabel labelHeader1;
    private javax.swing.JLabel labelHeader2;
    private javax.swing.JLabel labelHeader3;
    private javax.swing.JLabel labelHeader4;
    private javax.swing.JLabel labelPelaksanaan;
    private javax.swing.JLabel labelUjian;
    private javax.swing.JLabel labelUploadSoal;
    private javax.swing.JLabel labelUploadSoal2;
    private javax.swing.JLabel labelUploadSoal3;
    private javax.swing.JLabel labelUploadSoal4;
    private javax.swing.JLabel labelUploadSoal5;
    private com.jtk.pengelolaanujian.view.dashboard.PiePanelUjian piePanelUjian1;
    private javax.swing.JProgressBar progresEvent;
    private javax.swing.JTable tableUjian;
    private javax.swing.JTextField textEventAkhir;
    private javax.swing.JTextField textEventMulai;
    private javax.swing.JTextField textNilaiAkhir;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField textSoalAkhir;
    private javax.swing.JTextField textSoalMulai;
    private javax.swing.JTextField textUjian;
    private javax.swing.JTextField textVnvAkhir;
    private javax.swing.JTextField textVnvMulai;
    // End of variables declaration//GEN-END:variables
}
