/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jtk.pengelolaanujian.view.dashboard;

/**
 *
 * @author pahlevi
 */
public class StatusUser extends javax.swing.JPanel {

    /**
     * Creates new form StatusUser
     */
    public StatusUser() {
        initComponents();
    }

    public void preparation() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabeStatusAdmin2 = new com.jtk.pengelolaanujian.view.dashboard.TabeStatusAdmin();
        tabeStatusPanitia1 = new com.jtk.pengelolaanujian.view.dashboard.TabeStatusPanitia();
        tabeStatusDosenPengampu1 = new com.jtk.pengelolaanujian.view.dashboard.TabeStatusDosenPengampu();
        tabeStatusVNV1 = new com.jtk.pengelolaanujian.view.dashboard.TabeStatusVNV();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(609, 462));

        jTabbedPane1.addTab("Admin", tabeStatusAdmin2);
        jTabbedPane1.addTab("Panitia", tabeStatusPanitia1);
        jTabbedPane1.addTab("Dosen Pengampu", tabeStatusDosenPengampu1);
        jTabbedPane1.addTab("VNV", tabeStatusVNV1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tabel Monitoring Status Staff dalam Ujian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.jtk.pengelolaanujian.view.dashboard.TabeStatusAdmin tabeStatusAdmin2;
    private com.jtk.pengelolaanujian.view.dashboard.TabeStatusDosenPengampu tabeStatusDosenPengampu1;
    private com.jtk.pengelolaanujian.view.dashboard.TabeStatusPanitia tabeStatusPanitia1;
    private com.jtk.pengelolaanujian.view.dashboard.TabeStatusVNV tabeStatusVNV1;
    // End of variables declaration//GEN-END:variables
}
