/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.dashboard;

import com.jtk.pengelolaanujian.view.MainFrame;
import com.sun.org.apache.xalan.internal.lib.ExsltDatetime;
import java.util.Date;

/**
 *
 * @author pahlevi
 */
public class StatusTransaksi extends javax.swing.JPanel {

    //MainFrame mainFrame = null;

    /**
     * Creates new form DashboardPanel2
     */
    public StatusTransaksi() {
        //this.mainFrame = mainFrame;
        initComponents();
    }

    public void preparation() {
        Date date = new Date();
        piePanelNilai.preparation();
        piePanelSoal.preparation();
        piePanelVnv.preparation();
        piePanelVnv1.preparation();
        lableDate.setText(date.toLocaleString());                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piePanelVnv1 = new com.jtk.pengelolaanujian.view.dashboard.PiePanelVnv();
        piePanelNilai = new com.jtk.pengelolaanujian.view.dashboard.PiePanelNilai();
        piePanelVnv = new com.jtk.pengelolaanujian.view.dashboard.PiePanelVnv();
        piePanelSoal = new com.jtk.pengelolaanujian.view.dashboard.PiePanelSoal();
        labelDate2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelDate1 = new javax.swing.JLabel();
        lableDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        labelDate2.setText("Date :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Grafik Monotoring Status Transaksi Soal & Nilai");

        labelDate1.setText("Detail Informasi Transaksi dalam simple grafik");

        lableDate.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDate2)
                                .addGap(18, 18, 18)
                                .addComponent(lableDate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(piePanelSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piePanelVnv, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piePanelNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(labelDate1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDate2)
                    .addComponent(lableDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(piePanelVnv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(piePanelNilai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(piePanelSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(labelDate1)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDate1;
    private javax.swing.JLabel labelDate2;
    private javax.swing.JLabel lableDate;
    private com.jtk.pengelolaanujian.view.dashboard.PiePanelNilai piePanelNilai;
    private com.jtk.pengelolaanujian.view.dashboard.PiePanelSoal piePanelSoal;
    private com.jtk.pengelolaanujian.view.dashboard.PiePanelVnv piePanelVnv;
    private com.jtk.pengelolaanujian.view.dashboard.PiePanelVnv piePanelVnv1;
    // End of variables declaration//GEN-END:variables

}
