/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jtk.pengelolaanujian.view.dashboard;

import com.jtk.pengelolaanujian.controller.dashboard.TriggerDashboardController;
import com.jtk.pengelolaanujian.entity.Soal;

/**
 *
 * @author pahlevi
 */
public class TabeStatusVNV extends javax.swing.JPanel {
    TriggerDashboardController triggerDashboardController = new TriggerDashboardController();    
    
    /**
     * Creates new form TabeStatusAdmin
     */
    public TabeStatusVNV() {
        initComponents();
        
    }

     public void preparation() {
        triggerDashboardController.viewTableVnv(tabelStatusVNV);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelStatusVNV = new javax.swing.JTable();

        tabelStatusVNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "KBK", "email", "No. Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelStatusVNV);
        if (tabelStatusVNV.getColumnModel().getColumnCount() > 0) {
            tabelStatusVNV.getColumnModel().getColumn(0).setResizable(false);
            tabelStatusVNV.getColumnModel().getColumn(1).setResizable(false);
            tabelStatusVNV.getColumnModel().getColumn(2).setResizable(false);
            tabelStatusVNV.getColumnModel().getColumn(3).setResizable(false);
            tabelStatusVNV.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelStatusVNV;
    // End of variables declaration//GEN-END:variables
}
