/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.pengelolaanujian.view.util;

import com.jtk.pengelolaanujian.util.AsyncProgress;
import java.awt.Frame;
import javax.swing.SwingWorker;

/**
 *
 * @author Zulkhair Abdullah D
 */
public class LoadingDialog extends javax.swing.JDialog {

    private AsyncProgress asyncProgress;

    /**
     * Creates new form LoadingDialog
     */
    public LoadingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public LoadingDialog(AsyncProgress asyncProgress, Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
        this.asyncProgress = asyncProgress;
        setLocationRelativeTo(null);
    }

    public void start() {
        final LoadingDialog thisDialog = this;
        SwingWorker sw = new SwingWorker() {
            private LoadingDialog dialog = thisDialog;

            @Override
            protected void done() {
                dialog.setVisible(false);
                asyncProgress.done();
                dialog.dispose();
                super.done();
            }

            @Override
            protected Object doInBackground() throws Exception {
                asyncProgress.doInBackground();
                return null;
            }
        };
        sw.execute();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Loading .....");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sharereport/image/loading.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
